@startuml


  com.barlipdev.dwyf.controller.AuthController o-- com.barlipdev.dwyf.service.AuthService : authService
  com.barlipdev.dwyf.controller.OpenFoodProductController o-- com.barlipdev.dwyf.service.ProductsService : productsService
  com.barlipdev.dwyf.controller.PerformingRecipeController o-- com.barlipdev.dwyf.service.PerformingRecipeService : performingRecipeService
  com.barlipdev.dwyf.controller.RecipeController o-- com.barlipdev.dwyf.service.RecipeService : recipeService
  com.barlipdev.dwyf.controller.StatsController o-- com.barlipdev.dwyf.service.StatsService : statsService
  com.barlipdev.dwyf.controller.UserController o-- com.barlipdev.dwyf.service.UserService : userService
  com.barlipdev.dwyf.model.auth.LoginResponse o-- com.barlipdev.dwyf.model.user.User : user
  com.barlipdev.dwyf.model.product.Product .up.|> java.lang.Comparable
  com.barlipdev.dwyf.model.product.Product o-- com.barlipdev.dwyf.model.product.ProductType : productType
  com.barlipdev.dwyf.model.product.Product o-- com.barlipdev.dwyf.model.product.UsefulnessState : usefulnessState
  com.barlipdev.dwyf.model.recipe.MatchedRecipe o-- com.barlipdev.dwyf.model.recipe.Recipe : recipe
  com.barlipdev.dwyf.model.stats.PerformingRecipe o-- com.barlipdev.dwyf.model.recipe.MatchedRecipe : matchedRecipe
  com.barlipdev.dwyf.model.stats.PerformingRecipe o-- com.barlipdev.dwyf.model.recipe.RecipeStatus : recipeStatus
  com.barlipdev.dwyf.model.user.User o-- com.barlipdev.dwyf.model.user.UserRole : userRole
  com.barlipdev.dwyf.scheduler.ScheduledTasks o-- com.barlipdev.dwyf.service.UserService : userService
  com.barlipdev.dwyf.security.JwtFilter -up-|> org.springframework.security.web.authentication.www.BasicAuthenticationFilter
  com.barlipdev.dwyf.security.WebSecurityConfig .up.|> org.springframework.web.servlet.config.annotation.WebMvcConfigurer
  com.barlipdev.dwyf.security.WebSecurityConfig -up-|> org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
  com.barlipdev.dwyf.service.AuthService o-- com.barlipdev.dwyf.repository.UserRepository : userRepository
  com.barlipdev.dwyf.service.PerformingRecipeService o-- com.barlipdev.dwyf.repository.PerformingRecipeRepository : performingRecipeRepository
  com.barlipdev.dwyf.service.PerformingRecipeService o-- com.barlipdev.dwyf.service.UserService : userService
  com.barlipdev.dwyf.service.ProductsService o-- com.barlipdev.dwyf.repository.OpenFoodProductRepository : openFoodProductRepository
  com.barlipdev.dwyf.service.RecipeService o-- com.barlipdev.dwyf.service.PerformingRecipeService : performingRecipeService
  com.barlipdev.dwyf.service.RecipeService o-- com.barlipdev.dwyf.repository.RecipeRepository : recipeRepository
  com.barlipdev.dwyf.service.RecipeService o-- com.barlipdev.dwyf.service.UserService : userService
  com.barlipdev.dwyf.service.StatsService o-- com.barlipdev.dwyf.repository.RecipeRepository : recipeRepository
  com.barlipdev.dwyf.service.StatsService o-- com.barlipdev.dwyf.repository.UserRepository : userRepository
  com.barlipdev.dwyf.service.UserService o-- com.barlipdev.dwyf.mapper.Mapper : mapper
  com.barlipdev.dwyf.service.UserService o-- com.barlipdev.dwyf.repository.OpenFoodProductRepository : openFoodProductRepository
  com.barlipdev.dwyf.service.UserService o-- com.barlipdev.dwyf.repository.UserRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
